- name: setup ansible
  hosts: all
  remote_user: root
  become: true
  gather_facts: false

  tasks:
  - name: wget
    apt:
      name: wget
      state: latest

  - name: certificates
    command: apt install apt-transport-https software-properties-common -y
    become: yes
    become_method: sudo

  - name: add php repository
    command: add-apt-repository ppa:ondrej/php -y
    become: yes
    become_method: sudo 
         
  - name: gnupg
    apt:
      name: gnupg
      state: latest

  - name: Update and upgrade apt packages
    become: yes
    become_method: sudo
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: install php
    apt: 
      name: php8.1
      state: latest

  - name: install curl
    apt:
      name: curl
      state: latest

  - name: install git
    apt:
      name: git
      state: present

  - name: configure git username and password
    command: git config --global user.name "rigamortus"

  - name: configure email for git
    command: git config --global user.email "davidakalugo@gmail.com"

  - name: install php extensions
    apt:
      name: php-pgsql
      state: latest

  - name: install php extensions
    apt:
      name: php-mysql
      state: latest

  - name: install php extensions
    apt:
      name: php-xml
      state: latest

  - name: install php extensions
    apt:
      name: php-curl
      state: latest

  - name: install php extensions
    apt:
      name: php-mbstring
      state: latest

  - name: install php extensions
    apt:
      name: php-zip
      state: latest

  - name: install php extensions
    apt:
      name: php-fpm
      state: latest

  - name: install php extensions
    apt:
      name: libapache2-mod-php
      state: latest

  - name: clone laravel project
    git:
      repo: https://github.com/f1amy/laravel-realworld-example-app.git
      dest: /root/laravel_realworld
      force: yes
      accept_hostkey: yes

  - name: move laravel app
    shell: mv /root/laravel_realworld /var/www/html
    become: yes
    become_method: sudo

  - name: update psql repository
    ansible.builtin.apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present
      keyring: /usr/share/keyrings/postgresql-keyring.gpg

  - name: add psql repository
    command: echo "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql.list
 
  - name: update general repository
    register: updatesys
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: install psycog2
    apt:
      name: python3-pip
      state: present

  - name: add python utility
    ansible.builtin.package:
      name: python3-psycopg2
      state: present

  - name: add python dev
    apt:
      name: python3-dev
      state: present

  - name: update repo
    apt:
      name: postgresql-server-dev-all
      state: present

  - name: command
    command: pip install psycopg2-binary

  - name: update existing repositories
    become: yes
    become_method: sudo
    apt:
      update_cache: yes
      cache_valid_time: 86400
      force_apt_get: yes

  - name: install mysql shell
    become: yes
    become_method: sudo
    apt:
      name: mysql-server
      state: present
      force_apt_get: yes

  - name: install mysql shell
    become: yes
    become_method: sudo
    apt:
      name: mysql-client
      state: present
      force_apt_get: yes

  - name: install mysql shell
    become: yes
    become_method: sudo
    apt:
      name: python3-mysqldb
      state: present
      force_apt_get: yes

  - name: install mysql shell
    become: yes
    become_method: sudo
    apt:
      name: libmysqlclient-dev
      state: present
      force_apt_get: yes

  - name: ensure mysql starts at beginning
    service:
      name: mysql
      state: started
      enabled: yes
    become: yes

  - name: create user
    mysql_user: 
      name: laravel
      password: Phunkeeb100*
      check_implicit_admin: yes
      priv: '*.*:ALL'
      host: '%'
      state: present

  - name: create database
    mysql_db:
      name: laravel_realworld
      state: present
      login_user: root
      login_password: Phunkeeb100*

  - name: run psql bashscript
    script: /home/vagrant/ansible/ansible.sh

  - name: get composer
    shell:  curl -sS https://getcomposer.org/installer | php

  - name: rename composer.phar to composer
    shell: mv composer.phar /usr/local/bin/composer
    args:
      creates: /usr/local/bin/composer

  - name: make composer executable
    file:
      path: /usr/local/bin/composer
      mode: a+x
      state: file

  - name: install apache
    apt:
       name: apache2
       state: present

  - name: change permissions
    shell: sudo chgrp -R www-data /var/www/html/laravel_realworld/

  - name: change permission 2
    shell: sudo chmod -R 775 /var/www/html/laravel_realworld/storage

  - name: remove default apache config
    file:
      name: /etc/apache2/sites-enabled/000-default.conf
      state: absent

  - name: change environment variable
    command: cp /var/www/html/laravel_realworld/.env.example /var/www/html/laravel_realworld/.env

  - name: composer script
    script: /home/vagrant/ansible/composer.sh
    args:
      chdir: /var/www/html/laravel_realworld

  - name: generate php key
    command: php artisan key:generate
    args:
      chdir: /var/www/html/laravel_realworld

  - name: change .env file
    script: /home/vagrant/ansible/regex.sh
    args:
      chdir: /var/www/html/laravel_realworld
  
  - name: move php key
    command: php artisan migrate
    args:
      chdir: /var/www/html/laravel_realworld

  - name: set default conf
    template:
      src: /home/vagrant/ansible/laravel_realworld.conf
      dest: /etc/apache2/sites-available/laravel_realworld.conf

  - name: update a2ensite
    command: a2ensite laravel_realworld.conf

  - name: enable apache
    command: a2enmod rewrite

  - name: restart apache
    command: systemctl restart apache2

  - name: Uncomment line from web.php
    blockinfile:
      path: /var/www/html/laravel_realworld/routes/web.php
      state: present
      insertafter: EOF
      block: |
        Route::get('/', function () {
            return view('welcome');
        });     
